code --install-extension alefragnani.bookmarks
code --install-extension alefragnani.project-manager
code --install-extension bierner.github-markdown-preview
code --install-extension bierner.markdown-checkbox
code --install-extension bierner.markdown-emoji
code --install-extension bierner.markdown-footnotes
code --install-extension bierner.markdown-mermaid
code --install-extension bierner.markdown-preview-github-styles
code --install-extension bierner.markdown-yaml-preamble
code --install-extension bradlc.vscode-tailwindcss
code --install-extension chadalen.vscode-jetbrains-icon-theme
code --install-extension christian-kohler.path-intellisense
code --install-extension dbaeumer.vscode-eslint
code --install-extension dcortes92.freemarker
code --install-extension dotjoshjohnson.xml
code --install-extension eamodio.gitlens
code --install-extension ecmel.vscode-html-css
code --install-extension esbenp.prettier-vscode
code --install-extension formulahendry.auto-close-tag
code --install-extension formulahendry.auto-complete-tag
code --install-extension formulahendry.auto-rename-tag
code --install-extension github.copilot-chat
code --install-extension gruntfuggly.todo-tree
code --install-extension humao.rest-client
code --install-extension jeronimoekerdt.color-picker-universal
code --install-extension jzmstrjp.color-the-tag-name
code --install-extension k--kato.intellij-idea-keybindings
code --install-extension lokalise.i18n-ally
code --install-extension ms-azuretools.vscode-containers
code --install-extension ms-edgedevtools.vscode-edge-devtools
code --install-extension ms-vscode.hexeditor
code --install-extension ms-vscode.live-server
code --install-extension ms-vsliveshare.vsliveshare
code --install-extension oxc.oxc-vscode
code --install-extension pranaygp.vscode-css-peek
code --install-extension redhat.java
code --install-extension redhat.vscode-yaml
code --install-extension ritwickdey.liveserver
code --install-extension sdras.vue-vscode-snippets
code --install-extension shd101wyy.markdown-preview-enhanced
code --install-extension simonsiefke.svg-preview
code --install-extension sonarsource.sonarlint-vscode
code --install-extension streetsidesoftware.code-spell-checker
code --install-extension streetsidesoftware.code-spell-checker-ukrainian
code --install-extension stylelint.vscode-stylelint
code --install-extension syler.sass-indented
code --install-extension techer.open-in-browser
code --install-extension trinm1709.dracula-theme-from-intellij
code --install-extension tyriar.lorem-ipsum
code --install-extension upstash.context7-mcp
code --install-extension vitest.explorer
code --install-extension vscjava.vscode-gradle
code --install-extension vscjava.vscode-java-debug
code --install-extension vscjava.vscode-java-dependency
code --install-extension vscjava.vscode-java-pack
code --install-extension vscjava.vscode-java-test
code --install-extension vscjava.vscode-maven
code --install-extension vue.volar
code --install-extension webben.browserslist
code --install-extension zignd.html-css-class-completion
